spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ontoevolve
    username: ontoevolve
    password: ontoevolve123
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
